export const SET_SEARCH_LISTING = 'SET_SEARCH_LISTING';
// categories
export const SET_ALL_CATEGORIES = 'SET_ALL_CATEGORIES';
export const SET_ACTIVE_CATEGORY = 'SET_ACTIVE_CATEGORY'
export const SET_FOCUS_INPUT = 'SET_FOCUS_INPUT'
export const SET_FOCUS_CARD = 'SET_FOCUS_CARD'
export const SET_FOCUS_Menu = 'SET_FOCUS_Menu'
export const SET_LIST_NEIGHBORHOODS = 'SET_LIST_NEIGHBORHOODS'
export const SET_ACTIVE_NEIGHBORHOODS = 'SET_ACTIVE_NEIGHBORHOODS'