export const SET_SEARCH_LISTING = 'SET_SEARCH_LISTING';
// categories
export const SET_ALL_CATEGORIES = 'SET_ALL_CATEGORIES';
export const SET_ACTIVE_CATEGORY = 'SET_ACTIVE_CATEGORY'
export const SET_FOCUS_INPUT = 'SET_FOCUS_INPUT'